# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Working with Corpora
tagline:          'Information about our lessons and participants'
description:      'Working with Corpora (wowico) is an organisation that gives open-source lessons relating to corpus linguistics at Saarland Uni.'
url:              https://github.com/wowico
baseurl:          /

author:
  name:           'The Team'
  url:            https://github.com/wowico

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/wowico/wwc

collections:
- friends

collections:
  friends:
    output: true
    title: 'Friends'

defaults:
  - scope:
      path: ""
      relave_path: "/wwc/"
      type: friends
    values:
      layout: page